name: PHPUnit Tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl, dom, pdo_mysql

    - name: Move to src directory
      run: cd src

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      working-directory: ./src

    - name: Create .env file
      run: |
        cp .env.example .env
        php artisan key:generate
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
      working-directory: ./src

    - name: Run migrations
      run: php artisan migrate --seed
      working-directory: ./src

    - name: Run PHPUnit tests
      run: php artisan test
      working-directory: ./src
