name: PHPUnit Tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl, dom, pdo_mysql

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      working-directory: ./src

    - name: Create .env file
      run: |
        cp .env.example .env
        php artisan key:generate
        echo "APP_NAME=Laravel" >> .env
        echo "APP_ENV=local" >> .env
        echo "APP_KEY=base64:XDKQWNUwTOSBmMCIlWeQcMCA/O2I//lJ98MoMQpymvo=" >> .env
        echo "APP_DEBUG=true" >> .env
        echo "APP_URL=http://localhost" >> .env
        echo "LOG_CHANNEL=stack" >> .env
        echo "LOG_DEPRECATIONS_CHANNEL=null" >> .env
        echo "LOG_LEVEL=debug" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=coachtech-dev-rds.cdo6s60ie65j.ap-northeast-1.rds.amazonaws.com" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=coachtech" >> .env
        echo "DB_USERNAME=coachtech_admin" >> .env
        echo "DB_PASSWORD=coachtech_admin" >> .env
        echo "BROADCAST_DRIVER=log" >> .env
        echo "CACHE_DRIVER=file" >> .env
        echo "FILESYSTEM_DRIVER=local" >> .env
        echo "QUEUE_CONNECTION=sync" >> .env
        echo "SESSION_DRIVER=file" >> .env
        echo "SESSION_LIFETIME=120" >> .env
        echo "MEMCACHED_HOST=127.0.0.1" >> .env
        echo "REDIS_HOST=127.0.0.1" >> .env
        echo "REDIS_PASSWORD=null" >> .env
        echo "REDIS_PORT=6379" >> .env
        echo "MAIL_MAILER=smtp" >> .env
        echo "MAIL_HOST=mailhog" >> .env
        echo "MAIL_PORT=1025" >> .env
        echo "MAIL_USERNAME=null" >> .env
        echo "MAIL_PASSWORD=null" >> .env
        echo "MAIL_ENCRYPTION=null" >> .env
        echo "MAIL_FROM_ADDRESS=example@example.com" >> .env
        echo "MAIL_FROM_NAME='Example App'" >> .env
        echo "AWS_ACCESS_KEY_ID=" >> .env
        echo "AWS_SECRET_ACCESS_KEY=" >> .env
        echo "AWS_DEFAULT_REGION=ap-northeast-1" >> .env
        echo "AWS_BUCKET=coachtech-dev-bucket" >> .env
        echo "AWS_USE_PATH_STYLE_ENDPOINT=false" >> .env
        echo "PUSHER_APP_ID=" >> .env
        echo "PUSHER_APP_KEY=" >> .env
        echo "PUSHER_APP_SECRET=" >> .env
        echo "PUSHER_APP_CLUSTER=mt1" >> .env
        echo "MIX_PUSHER_APP_KEY=\${PUSHER_APP_KEY}" >> .env
        echo "MIX_PUSHER_APP_CLUSTER=\${PUSHER_APP_CLUSTER}" >> .env
        echo "STRIPE_KEY=pk_test_51PMXG9B1opHs8wxjQTgDILBqyXbHXDGcUfyFc134ZCYD0LicIgKFIrZAyMa1uIMyFYLctx2ijub02ugmwoWM8NPl00qtj2Y0OH" >> .env
        echo "STRIPE_SECRET=sk_test_51PMXG9B1opHs8wxjPy15mmOWDgq5ve1RmruYM2MXOa10QWJTdzktoc9Eduacx7nCgvhqaRtZj4SxwZ4BeyTIXGNG00QmyTePHK" >> .env
        cat .env
      working-directory: ./src

    - name: Check MySQL connection
      run: |
        sudo apt-get install -y mysql-client
        mysql -h coachtech-dev-rds.cdo6s60ie65j.ap-northeast-1.rds.amazonaws.com -P 3306 -u coachtech_admin -pcoachtech_admin -e "SHOW DATABASES;"
      working-directory: ./src

    - name: Run migrations
      run: php artisan migrate --seed
      working-directory: ./src

    - name: Run PHPUnit tests
      run: php artisan test
      working-directory: ./src
