name: PHPUnit Tests and Deploy

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl, dom, pdo_mysql

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      working-directory: ./src

    - name: Create .env file
      run: |
        cp .env.example .env
        php artisan key:generate
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        cat .env  # .env ファイルの内容を確認するためのログ
      working-directory: ./src

    - name: Create SSH Tunnel and Run MySQL commands
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem -L 3306:${{ secrets.DB_HOST }}:3306 ec2-user@${{ secrets.EC2_HOST }} -N &
        sleep 15  # Ensure the tunnel is established
        mysql -h 127.0.0.1 -P 3306 -u "${{ secrets.DB_USERNAME }}" -p"${{ secrets.DB_PASSWORD }}" -e "SHOW DATABASES;"
      working-directory: ./src

    - name: Run migrations
      run: php artisan migrate --seed
      working-directory: ./src

    - name: Run PHPUnit tests
      run: php artisan test
      working-directory: ./src

    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ secrets.EC2_HOST }} 'bash -s' < deploy.sh
